/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const _kFontPkg = null;

  static const IconData youtube_squared =
      IconData(0xf166, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_squared =
      IconData(0xf199, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medium =
      IconData(0xf23a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_squared =
      IconData(0xf300, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter_squared =
      IconData(0xf304, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_squared =
      IconData(0xf308, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discord =
      IconData(0xf392, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
